### ISSUE TITLE
Error: SQLITE_NOTADB: file is not a database

### ISSUE THREAD

**Issue by Ivorfason** [journeyapps/node-sqlcipher#25] opened 2019-12-11 10:03 UTC
when I first time starting my electron app, It created xxx.db can insert data within no problem.
but when I restart my app, It got an error: **Error: SQLITE_NOTADB: file is not a database.**
The xxx.db file exists actually, and I can open it with passport well.

here is my code: 
`const sqlite3 = require('@journeyapps/sqlcipher').verbose()`
`const db = new sqlite3.Database('./xxx.db'))`
`db.run('PRAGMA cipher_compatibility = 3')`
`db.run("PRAGMA key = 'abc'")`
`db.run('PRAGMA page_size=1024')`

**Comment by liederivative** [comment] 2019-12-23 14:25
@Ivorfason Did you run all your code inside db.serialize function ? Remember that each db.run should be sequential in order to work.

**Comment by Christilut** [comment] 2020-04-16 06:32
I have the same problem when trying to open a database in my Jest test.

In Electron everything works (btw, thanks for this library, annoying to get working without!) but when running a simple `new sqlite3.Database(databasePath)` it show the error `SQLITE_NOTADB: file is not a database`. The path does exist.

Maybe an OpenSSL issue? But I'm not sure how to resolve this

**Comment by liederivative** [comment] 2020-04-17 02:30
Well, without looking at your implementation it's hard to tell, but sometimes that error means the db is already encrypted and the encryption key is wrong or anything related to the encryption method, like a wrong page_size, etc (assuming everything is fine with openssl) . Again, hard to tell without knowing your implementation.

**Comment by Christilut** [comment] 2020-04-17 07:16
You're right, it was my own fault! The PRAGMA call was missing in the test environment which caused this unhelpful generic error by SQLite :/

**Comment by rkistner** [comment] 2020-09-25 13:22
The generic message is because sqlcipher cannot distinguish between an invalid/corrupted file, versus incorrect cipher settings or key. There isn't any good way around this given sqlcipher's design.

Closing this issue for now - feel free to open another issue if there is a reproducable test case for this.

**Closed by rkistner** 2020-09-25 13:22 UTC

**Comment by emanavas** [comment] 2022-10-10 17:04
I get that error when the passoword key its no correct. check that. You can use [sqlite browser](https://sqlitebrowser.org/dl/) for access the DB and check data its corrupted (GUI interface)
