### ISSUE TITLE
Compiling fails on Linux

### ISSUE THREAD

**Issue by flberger** [journeyapps/node-sqlcipher#8] opened 2018-08-04 10:02 UTC
Doing an `npm install @journeyapps/sqlcipher`, I get lots of errors of the sort

    /usr/lib/gcc/i686-pc-linux-gnu/7.3.0/../../../../i686-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file './Release/obj/gen/sqlcipher-amalgamation-3020001/OpenSSL-Linux/libcrypto.a(ecp_smpl.o)' is incompatible with i386 output

and finally

    ./Release/obj/gen/sqlcipher-amalgamation-3020001/OpenSSL-Linux/libcrypto.a(dso_dlfcn.o): In function 'dlfcn_globallookup':
    dso_dlfcn.c:(.text+0x11): undefined reference to 'dlopen'
    dso_dlfcn.c:(.text+0x24): undefined reference to 'dlsym'
    dso_dlfcn.c:(.text+0x2f): undefined reference to 'dlclose'
    ./Release/obj/gen/sqlcipher-amalgamation-3020001/OpenSSL-Linux/libcrypto.a(dso_dlfcn.o): In function 'dlfcn_bind_func':
    dso_dlfcn.c:(.text+0x334): undefined reference to 'dlsym'
    dso_dlfcn.c:(.text+0x3f2): undefined reference to 'dlerror'
    ./Release/obj/gen/sqlcipher-amalgamation-3020001/OpenSSL-Linux/libcrypto.a(dso_dlfcn.o): In function 'dlfcn_bind_var':
    dso_dlfcn.c:(.text+0x464): undefined reference to 'dlsym'
    dso_dlfcn.c:(.text+0x522): undefined reference to 'dlerror'
    ./Release/obj/gen/sqlcipher-amalgamation-3020001/OpenSSL-Linux/libcrypto.a(dso_dlfcn.o): In function 'dlfcn_load':
    dso_dlfcn.c:(.text+0x589): undefined reference to 'dlopen'
    dso_dlfcn.c:(.text+0x5ed): undefined reference to 'dlclose'
    dso_dlfcn.c:(.text+0x625): undefined reference to 'dlerror'
    ./Release/obj/gen/sqlcipher-amalgamation-3020001/OpenSSL-Linux/libcrypto.a(dso_dlfcn.o): In function 'dlfcn_pathbyaddr':
    dso_dlfcn.c:(.text+0x6b1): undefined reference to 'dladdr'
    dso_dlfcn.c:(.text+0x711): undefined reference to 'dlerror'
./Release/obj/gen/sqlcipher-amalgamation-3020001/OpenSSL-Linux/libcrypto.a(dso_dlfcn.o): In function 'dlfcn_unload':
    dso_dlfcn.c:(.text+0x772): undefined reference to 'dlclose'

    npm ERR! Failed at the @journeyapps/sqlcipher@3.2.1 install script 'node-pre-gyp install --build-from-source'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the @journeyapps/sqlcipher package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --build-from-source

**Comment by rkistner** [comment] 2018-08-06 07:18
Are you running on a 32-bit Linux installation, or 32-bit Node? This has been tested on 64-bit, but not on 32-bit yet, which could explain the errors.

That said, there isn't anything specific to 64-bit in this repo, but it should be possible to get it working. If you do get it working, please let me know, so I can update the instructions.

**Comment by johannfr** [comment] 2018-09-04 16:28
Having the same problem. Yes, running 32-bit as well. This is because the libcypher.a file you have in your amalgamation tarball (under OpenSSL-Linux) has only 64-bit objects in it. So there is indeed something very 64-bit specific in here.

**Comment by rkistner** [comment] 2018-09-05 08:18
That's strange, there is no reference to OpenSSL-Linux anywhere in this project that I could find, and libcypher.a is not bundled with this project either. We only use the bundled OpenSSL binaries for Windows - for Linux and MacOS we use the system libraries.

Do you get the same when cloning this project, instead of installing via npm?

**Comment by johannfr** [comment] 2018-09-28 11:55
For some reason it's using a bundled version of those binaries on Linux but not the system ones.
I ended up just buying a new (64-bit) PC so I can now simply install a pre-compiled Signal client (which are only available as 64-bit binaries, not 32-bit. Signal depends on this package by proxy), so no, I haven't tried to clone the project. I won't be spending more time on this.

**Comment by rkistner** [comment] 2018-10-01 10:38
Closing for now, since this seems to be related to a different project. Can re-open if we have more specific steps to reproduce the issue.

**Comment by SevereOverfl0w** [comment] 2018-10-14 06:31
We're seeing this issue when trying to build a package which depends on node-sqlcipher. Full output for the failing build is available on travis: https://travis-ci.org/void-linux/void-packages/jobs/435671155#L4115

**Comment by johannfr** [comment] 2018-10-14 09:46
The interesting bit is close to the end of the log:
./Release/obj/gen/sqlcipher-amalgamation-3020001/OpenSSL-Linux/libcrypto.a: error adding symbols: File format not recognized collect2: error: ld returned 1 exit status

This is caused by the build trying to use the 64-bit version of the library from the amalgamation archive (instead of the system one) for a 32-bit (i686) build.

**Comment by johannfr** [comment] 2018-10-14 09:52
But I have no idea where the problem comes from, node-sqlcipher or Signal-desktop. This was the first and only time I've tried to build or install anything Node.js related, so I have no idea how those buildsystems work and who's defining what (e.g. library paths, dependencies, etc.)

**Comment by rkistner** [comment] 2018-10-14 19:45
@SevereOverfl0w Thanks, that link helped find the cause. So the Signal-Desktop build uses a fork of this project:
```
"@journeyapps/sqlcipher": "https://github.com/scottnonnenberg-signal/node-sqlcipher.git#ed4f4d179ac010c6347b291cbd4c2ebe5c773741"
```

That is this branch:

https://github.com/journeyapps/node-sqlcipher/compare/master...scottnonnenberg-signal:updates?expand=1

So the fork includes a bundled version of OpenSSL for Linux, but only the 64-bit version. So technically it's a bug in the fork and not this project, but I'll consider it a feature request to add a bundled version for Linux and MacOS.

**Comment by andreasspeck** [comment] 2019-06-04 13:27
Any news on this? I'm running into this trying to build Signal for 32bit on Debian. I'm aware this is related to the forked repo at https://github.com/scottnonnenberg-signal/node-sqlcipher

**Comment by rkistner** [comment] 2019-07-05 11:22
At this point, supporting 32-bit Linux in this package is not worth it for us, with even Ubuntu not properly supporting 32-bit applications anymore.

However, if someone else decides to implement the required changes, pull requests will be accepted.

**Closed by rkistner** 2019-07-05 11:22 UTC
